move2kube:
  minreplicas: "2"
  services:
    pacman:
      "8080":
        servicetype: Ingress
        urlpath: /
      enable: true
      port: "8080"
  target:
    default:
      clustertype: Openshift
      ingress:
        host: pacman-m2k.apps-crc.testing
    imageregistry:
      namespace: antoniora
      quay.io:
        logintype: username and password
        username: antoniora
      url: quay.io
  transformers:
    types:
      - Rust-Dockerfile
      - Knative
      - DockerfileDetector
      - Ruby-Dockerfile
      - Kubernetes
      - WinWebApp-Dockerfile
      - Tomcat
      - PHP-Dockerfile
      - Gradle
      - Jboss
      - ClusterSelector
      - CloudFoundry
      - Nodejs-Dockerfile
      - Liberty
      - Maven
      - DockerfileImageBuildScript
      - DotNetCore-Dockerfile
      - ComposeGenerator
      - Buildconfig
      - ReadMeGenerator
      - Python-Dockerfile
      - Parameterizer
      - Golang-Dockerfile
      - ArgoCD
      - ComposeAnalyser
      - WarAnalyser
      - EarAnalyser
      - EarRouter
      - Tekton
      - ZuulAnalyser
      - KubernetesVersionChanger
      - Jar
      - WarRouter
      - ContainerImagesPushScriptGenerator
      - DockerfileParser
  transformerselector: ""
