apiVersion: move2kube.konveyor.io/v1alpha1
kind: QACache
spec:
  solutions:
    - id: move2kube.transformerselector
      type: Input
      description: Specify a Kubernetes style selector to select only the transformers that you want to run.
      hints:
        - Leave empty to select everything. This is the default.
      default: ""
      answer: ""
    - id: move2kube.transformers.types
      type: MultiSelect
      description: 'Select all transformer types that you are interested in:'
      hints:
        - Services that don't support any of the transformer types you are interested in will be ignored.
      options:
        - ArgoCD
        - Buildconfig
        - CloudFoundry
        - ClusterSelector
        - ComposeAnalyser
        - ComposeGenerator
        - ContainerImagesPushScriptGenerator
        - DockerfileDetector
        - DockerfileImageBuildScript
        - DockerfileParser
        - DotNetCore-Dockerfile
        - EarAnalyser
        - EarRouter
        - Golang-Dockerfile
        - Gradle
        - Jar
        - Jboss
        - Knative
        - Kubernetes
        - KubernetesVersionChanger
        - Liberty
        - Maven
        - Nodejs-Dockerfile
        - PHP-Dockerfile
        - Parameterizer
        - Python-Dockerfile
        - ReadMeGenerator
        - Ruby-Dockerfile
        - Rust-Dockerfile
        - Tekton
        - Tomcat
        - WarAnalyser
        - WarRouter
        - WinWebApp-Dockerfile
        - ZuulAnalyser
      default:
        - Nodejs-Dockerfile
        - Kubernetes
        - ContainerImagesPushScriptGenerator
        - DockerfileDetector
        - DockerfileParser
        - ReadMeGenerator
        - Jar
        - DotNetCore-Dockerfile
        - Golang-Dockerfile
        - Jboss
        - ArgoCD
        - Rust-Dockerfile
        - ZuulAnalyser
        - DockerfileImageBuildScript
        - Gradle
        - Liberty
        - WarAnalyser
        - EarAnalyser
        - Parameterizer
        - Tekton
        - ClusterSelector
        - Tomcat
        - EarRouter
        - KubernetesVersionChanger
        - CloudFoundry
        - WinWebApp-Dockerfile
        - WarRouter
        - ComposeGenerator
        - Knative
        - PHP-Dockerfile
        - Maven
        - ComposeAnalyser
        - Buildconfig
        - Ruby-Dockerfile
        - Python-Dockerfile
      answer:
        - Nodejs-Dockerfile
        - Kubernetes
        - ContainerImagesPushScriptGenerator
        - DockerfileDetector
        - DockerfileParser
        - ReadMeGenerator
        - Jar
        - DotNetCore-Dockerfile
        - Golang-Dockerfile
        - Jboss
        - ArgoCD
        - Rust-Dockerfile
        - ZuulAnalyser
        - DockerfileImageBuildScript
        - Gradle
        - Liberty
        - WarAnalyser
        - EarAnalyser
        - Parameterizer
        - Tekton
        - ClusterSelector
        - Tomcat
        - EarRouter
        - KubernetesVersionChanger
        - CloudFoundry
        - WinWebApp-Dockerfile
        - WarRouter
        - ComposeGenerator
        - Knative
        - PHP-Dockerfile
        - Maven
        - ComposeAnalyser
        - Buildconfig
        - Ruby-Dockerfile
        - Python-Dockerfile
    - id: move2kube.services.[].enable
      type: MultiSelect
      description: 'Select all services that are needed:'
      hints:
        - The services unselected here will be ignored.
      options:
        - pacman
      default:
        - pacman
      answer:
        - pacman
    - id: move2kube.services."pacman".port
      type: Select
      description: 'Select the port to be exposed for the ''"pacman"'' service :'
      hints:
        - Select 'Other' if you want to expose the service using a different port.
      options:
        - "8080"
        - Other (specify custom option)
      default: "8080"
      answer: "8080"
    - id: move2kube.target.imageregistry.url
      type: Select
      description: 'Enter the URL of the image registry where the new images should be pushed : '
      hints:
        - You can always change it later by changing the yamls.
      options:
        - Other (specify custom option)
        - quay.io
      default: quay.io
      answer: quay.io
    - id: move2kube.target.imageregistry.namespace
      type: Input
      description: 'Enter the namespace where the new images should be pushed : '
      hints:
        - 'Ex : pacman'
      default: pacman
      answer: pacman
    - id: move2kube.target."default".clustertype
      type: Select
      description: 'Choose the cluster type:'
      hints:
        - Choose the cluster type you would like to target
      options:
        - GCP-GKE
        - IBM-IKS
        - IBM-Openshift
        - Kubernetes
        - Openshift
        - AWS-EKS
        - Azure-AKS
      default: Kubernetes
      answer: Openshift
    - id: move2kube.services."pacman"."8080".servicetype
      type: Select
      description: What kind of service/ingress should be created for the service pacman's 8080 port?
      hints:
        - Choose Ingress if you want a ingress/route resource to be created
      options:
        - Ingress
        - LoadBalancer
        - NodePort
        - ClusterIP
        - Don't create service
      default: Ingress
      answer: Ingress
    - id: move2kube.services."pacman"."8080".urlpath
      type: Input
      description: Specify the ingress path to expose the service pacman's 8080 port on?
      hints:
        - Leave out leading / to use first part as subdomain
      default: /pacman
      answer: /
    - id: move2kube.minreplicas
      type: Input
      description: Provide the minimum number of replicas each service should have
      hints:
        - If the value is 0 pods won't be started by default
      default: "2"
      answer: "2"
    - id: move2kube.target.imageregistry."quay.io".logintype
      type: Select
      description: '[quay.io] What type of container registry login do you want to use?'
      hints:
        - Docker login from config mode, will use the default config from your local machine.
      options:
        - use an existing pull secret
        - no authentication
        - username and password
      default: no authentication
      answer: username and password
    - id: move2kube.target.imageregistry."quay.io".username
      type: Input
      description: '[quay.io] Enter the username to login into the registry : '
      default: iamapikey
      answer: antoniora
    - id: move2kube.target."default".ingress.host
      type: Input
      description: Provide the ingress host domain
      hints:
        - Ingress host domain is part of service URL
      default: pacman.com
      answer: apps-crc.testing
