
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    creationTimestamp: null
    name: pacman-clone-build-push-pacman
spec:
    nodeSelector: null
    output:
        to:
            kind: ImageStreamTag
            name: pacman-latest:latest
    postCommit: {}
    resources: {}
    source:
        git:
            ref: main
            uri: ""
        sourceSecret:
            name: pacman-git-repo-generic
        type: Git
    strategy:
        dockerStrategy:
            dockerfilePath: '<TODO: insert path to the Dockerfile>'
        type: Docker
    triggers:
        - generic:
            secretReference:
                name: pacman-web-hook-pacman
          type: Generic
status:
    lastVersion: 0

...
