apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: antoniora-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerBinding
    metadata:
      creationTimestamp: null
      name: antoniora-git-event
    spec: {}
    status: {}
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: EventListener
    metadata:
      creationTimestamp: null
      name: antoniora-git-repo
    spec:
      namespaceSelector: {}
      resources: {}
      serviceAccountName: antoniora-tekton-triggers-admin
      triggers:
        - bindings:
            - ref: antoniora-git-event
          template:
            ref: antoniora-run-clone-build-push
    status:
      configuration:
        generatedName: ""
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: null
      name: antoniora-tekton-triggers-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: antoniora-tekton-triggers-admin
    subjects:
      - kind: ServiceAccount
        name: antoniora-tekton-triggers-admin
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: antoniora-tekton-triggers-admin
  - apiVersion: v1
    data:
      .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJZVzUwYjI1cGIzSmhPazFoWkhKcFpIQnNNVFV3TlE9PSIKCQl9Cgl9Cn0=
    kind: Secret
    metadata:
      creationTimestamp: null
      name: quay-io-imagepullsecret
    type: kubernetes.io/dockerconfigjson
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      creationTimestamp: null
      name: antoniora-clone-build-push
    spec:
      params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
      tasks:
        - name: clone-1
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: antoniora-shared-data
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/pacman
            - name: DOCKERFILE
              value: '<TODO: insert path to the Dockerfile>'
            - name: CONTEXT
              value: '<TODO: insert path to the directory containing Dockerfile>'
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: antoniora-shared-data
      workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: antoniora-shared-data
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: antoniora-clone-push
    secrets:
      - name: antoniora-image-registry
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: antoniora-git-repo
      name: antoniora-git-repo
    spec:
      host: pacman-m2k.apps-crc.testing
      path: /el-antoniora-git-repo
      port:
        targetPort: port-8080
      to:
        kind: Service
        name: antoniora-git-repo
        weight: 1
    status:
      ingress:
        - {}
  - apiVersion: v1
    data:
      .dockerconfigjson: PFRPRE86IGluc2VydCB5b3VyIGRvY2tlciBjb25maWcganNvbj4=
    kind: Secret
    metadata:
      annotations:
        tekton.dev/docker-0: ""
      creationTimestamp: null
      name: antoniora-image-registry
    type: kubernetes.io/dockerconfigjson
  - apiVersion: triggers.tekton.dev/v1alpha1
    kind: TriggerTemplate
    metadata:
      creationTimestamp: null
      name: antoniora-run-clone-build-push
    spec:
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            creationTimestamp: null
            name: antoniora-clone-build-push-$(uid)
          spec:
            params:
              - name: image-registry-url
                value: quay.io/antoniora
            pipelineRef:
              name: antoniora-clone-build-push
            serviceAccountName: antoniora-clone-push
            workspaces:
              - name: antoniora-shared-data
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    storageClassName: default
                  status: {}
          status: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: antoniora-tekton-triggers-admin
    rules:
      - apiGroups:
          - triggers.tekton.dev
        resources:
          - eventlisteners
          - triggerbindings
          - triggertemplates
        verbs:
          - get
      - apiGroups:
          - tekton.dev
        resources:
          - pipelineruns
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
parameters: []
