apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pacman-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: pacman-clone-build-push-pacman
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: pacman-latest:latest
      postCommit: {}
      resources: {}
      source:
        git:
          ref: main
          uri: ""
        sourceSecret:
          name: pacman-git-repo-generic
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: '<TODO: insert path to the Dockerfile>'
        type: Docker
      triggers:
        - generic:
            secretReference:
              name: pacman-web-hook-pacman
          type: Generic
    status:
      lastVersion: 0
  - apiVersion: v1
    data:
      ssh-privatekey: PFRPRE86IGluc2VydCB0aGUgcHJpdmF0ZSBzc2gga2V5IGZvciB5b3VyIGdpdCByZXBvPg==
    kind: Secret
    metadata:
      creationTimestamp: null
      name: pacman-git-repo-generic
    type: kubernetes.io/ssh-auth
  - apiVersion: v1
    data:
      WebHookSecretKey: N2RlNDkwODNlZTIyZTgwOA==
    kind: Secret
    metadata:
      creationTimestamp: null
      name: pacman-web-hook-pacman
    type: Opaque
parameters: []
