apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: pacman-run-clone-build-push
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        creationTimestamp: null
        name: pacman-clone-build-push-$(uid)
      spec:
        params:
          - name: image-registry-url
            value: quay.io/pacman
        pipelineRef:
          name: pacman-clone-build-push
        serviceAccountName: pacman-clone-push
        workspaces:
          - name: pacman-shared-data
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: default
              status: {}
      status: {}
status: {}
