apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: antoniora-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: pacman-latest
      name: pacman-latest
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: pacman
          generation: null
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ""
    status:
      dockerImageRepository: ""
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: pacman
      name: pacman
    spec:
      host: pacman-m2k.apps-crc.testing
      path: /
      port:
        targetPort: port-8080
      to:
        kind: Service
        name: pacman
        weight: 1
    status:
      ingress:
        - {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: pacman
      name: pacman
    spec:
      internalTrafficPolicy: Cluster
      ports:
        - name: port-8080
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        move2kube.konveyor.io/service: pacman
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    data:
      .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJZVzUwYjI1cGIzSmhPazFoWkhKcFpIQnNNVFV3TlE9PSIKCQl9Cgl9Cn0=
    kind: Secret
    metadata:
      creationTimestamp: null
      name: quay-io-imagepullsecret
    type: kubernetes.io/dockerconfigjson
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: pacman
      name: pacman
    spec:
      progressDeadlineSeconds: 600
      replicas: ${{COMMON_REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          move2kube.konveyor.io/service: pacman
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            move2kube.konveyor.io/service: pacman
          name: pacman
        spec:
          containers:
            - image: quay.io/antoniora/pacman:latest
              imagePullPolicy: Always
              name: pacman
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status: {}
parameters:
  - name: COMMON_REPLICAS
    value: "2"
